[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/app-ads.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "no-cache"

[[headers]]
  for = "/ads.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "no-cache" 